name: CI
on: push
jobs:
  Lint_and_test:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Node
      #   uses: actions/setup-node@v3

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Sdk
        run: turbo run build --filter @trythis/treblle-express
