name: CI
on: push
jobs:
  Lint_and_test:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Sdk
        run: turbo run build --filter @trythis/treblle-express
